apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-prod-cloud
  labels:
      config-revision: c9024ba83c893f902943548861bce4c79b6baef0  
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: cloud
    environment: prod
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: prod
        path: cloud
  workloadVersion:
    version: 0.0.1-37
    commit: 17872200c8228b54afe68df7072bfda197e6f228