apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-dev-performance-test
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: performance-test
    environment: dev
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: performance-test
  workloadVersion:
    version: 0.0.1-35
    commit: 2358f1f08ac6298d2e34e23e9abf816b4c763b5f