apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-stage-performance-test
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: performance-test
    environment: stage
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: stage
        path: performance-test
  workloadVersion:
    version: 0.0.1-29
    commit: a297953b3cc44aab7cbccd9adc479f87f5b152aa