apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-dev-performance-test
  labels:
      config-revision: 3095e20cded4cc39fc2842cd6bb4dbc2ee3cec04  
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: performance-test
    environment: dev
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: performance-test
  workloadVersion:
    version: 0.0.1-37
    commit: 17872200c8228b54afe68df7072bfda197e6f228