apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-dev-functional-test
  labels:
      config-revision: ba4c520e3ba5be72b73f44977a30883a3135adcd  
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: functional-test
    environment: dev
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: functional-test
  workloadVersion:
    version: 0.0.1-46
    commit: 7fd598b9f4ab660c3f985f5b045d00a29d6efade