apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-dev-int-test
  labels:
      config-revision: 3095e20cded4cc39fc2842cd6bb4dbc2ee3cec04  
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: int-test
    environment: dev
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: dev
        path: int-test
  workloadVersion:
    version: 0.0.1-40
    commit: e4d6ec9acc52b6e2de969f4442362fb871490e9f